refs platform/1307: hide drupal header by default
sparkfabrik/docker-php-drupal-nginx pull request #75
Opened 2022-04-13 13:36 UTC by Monska85

2022-04-13 17:35 UTC, paolomainardi commented
Merging this will make all the drupal apps also for development branches not printing these headers anymore, we can fix it by releasing a new package enabling but most of the projects will be affected.
Let's dig it more

2022-04-13 17:36 UTC, paolomainardi requested changes
We should understand better the effects on local/dev envs and how to handle them

2022-04-14 09:53 UTC, Monska85 commented
I have opened a MR to restore the headers in the package for the local and the review environments.

2022-04-27 15:31 UTC, Syphon83 approved these changes
LGTM ! Thank you !

2022-04-27 15:31 UTC, Syphon83 commented on docker-entrypoint.sh
> +export NGINX_XFRAME_OPTION_ENABLE="${NGINX_XFRAME_OPTION_ENABLE:-1}"
We should leave X-frame options header disabled by default, do you agree?

2022-04-27 15:31 UTC, Monska85 commented on docker-entrypoint.sh
> +export NGINX_XFRAME_OPTION_ENABLE="${NGINX_XFRAME_OPTION_ENABLE:-1}"
Disabled

2022-04-28 15:22 UTC, merged